package org.ispcluj;

//TODO: REQ-1
public record Train(String id, String type, String origin) {
    // you can create a classic Train class and delete this if it's better for you
    // here you can add extra methods if needed (getters, setters, hashCode, equals are already generated by the record)
    //check if toString works without generating it, if not and you need it, generate it.
    public String getId() {
        return id;
    }
    public String getType() {
        return type;
    }
    public String getOrigin() {
        return origin;
    }
    public void validateSignals() {
        //check and throw SignalFailureException if needed from here
        public void validateSignals() throws SignalFailureException {
            if (origin == null || origin.isBlank()) {
                throw new SignalFailureException("Train " + id + " has invalid origin signal.");
            }
        }

        @Override
        public String toString() {
            return "Train{id='" + id + "', type='" + type + "', origin='" + origin + "'}";
        }
    }


